apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: rg-fsapps-vaidy-devops-sbx
    service.beta.kubernetes.io/azure-dns-label-name: mydotnetappdemo
  name: dotnet-demoapp-load-balancer
spec:
  loadBalancerIP: 13.68.174.175
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    app: dotnet-demoapp
